# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ghcr.io/gdzhht/download-apk:main

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          cd fdroid
          echo 'keystorepass: '$keystorepass >> ./config.yml
          echo 'keypass: '$keypass >> ./config.yml
          echo $keystore > keystore.b64
          base64 -d keystore.b64 > ./keystore.p12
          fdroid update

      # Runs a set of commands using the runners shell
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: fdroid/repo # The folder the action should deploy.
